---
- name: Create placement database
  mysql_db:
    login_host: "{{db_node}}"
    login_user: "root"
    login_password: "{{mariadb_root_password}}"
    name: placement
    state: present
- name: Create placement user with necessary grants
  mysql_user:
    login_host: "{{db_node}}"
    login_user: "root"
    login_password: "{{mariadb_root_password}}"
    name: placement
    password: "{{placement_db_user_password}}"
    priv: 'placement.*:ALL'
    state: present
    host: "{{item}}"
  loop:
    - localhost
    - "%"
- name: Create placement user in keystone
  os_user:
    auth:
      auth_url: http://{{api_node}}:5000/v3
      username: admin
      os_user_domain_name: "default"
      os_project_domain_name: "default"
      os_project_name: "admin"
      password: "{{keystone_admin_password}}"
    auth_type: password
    description: "Placement user"
    name: "placement"
    domain: "default"
    password: "{{placement_keystone_user_password}}"
    state: present
- name: Assign admin role to newly created placement user
  os_user_role:
    auth:
      auth_url: http://{{api_node}}:5000/v3
      username: admin
      os_user_domain_name: "default"
      os_project_domain_name: "default"
      os_project_name: "admin"
      password: "{{keystone_admin_password}}"
    auth_type: password
    project: service
    user: placement
    role: admin
    state: present
- name: Create placement service entity
  os_keystone_service:
    auth:
      auth_url: http://{{api_node}}:5000/v3
      username: admin
      os_user_domain_name: "default"
      os_project_domain_name: "default"
      os_project_name: "admin"
      password: "{{keystone_admin_password}}"
    auth_type: password
    name: placement
    service_type: placement
    state: present
- name: Create endpoints
  os_keystone_endpoint:
    auth:
      auth_url: http://{{api_node}}:5000/v3
      username: admin
      os_user_domain_name: "default"
      os_project_domain_name: "default"
      os_project_name: "admin"
      password: "{{keystone_admin_password}}"
    auth_type: password
    endpoint_interface: "{{item}}"
    service: placement
    region: RegionOne
    url: "http://{{api_node}}:8778"
    state: present
  loop:
    - public
    - internal
    - admin
- name: Install placement package
  apt:
    force_apt_get: yes
    name: placement-api
    state: latest
- name: Create placement.conf
  template:
    src: "placement.conf.j2"
    dest: /etc/placement/placement.conf
    owner: root
    group: placement
    force: yes
    mode: 0644
- name: Sync placement database
  become_user: placement
  shell:
    placement-manage db sync
- name: Adjust Apache2 configuration for placement
  template:
    src: apache_placement.conf.j2
    dest: /etc/apache2/sites-available/placement-api.conf
    owner: root
    group: root 
    mode: 0644
- name: Restart Apache
  service:
    name: apache2
    state: restarted
