---
# The URL to download the CirrOS image from. Original URL is
# cirros_download_url: "http://download.cirros-cloud.net/0.4.0/
# As this is very slow, I have put the image into a public S3 bucket 
cirros_download_url: "https://s3.eu-central-1.amazonaws.com/cloud.leftasexercise.com"


